const a = 47;
const b = 9;
const sum = a + b;
const diff = a - b;
const multiply = a * b;
const divide = a / b;
const reminder = a % b;
console.log(sum);
console.log(diff);
console.log(multiply);
console.log(divide);
console.log(reminder);